# Generated by Django 4.2.2 on 2023-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0002_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(upload_to="ads/images/"),
        ),
    ]
